# Target device
MCU=cortex-m4

# Application files and targets
TARGET = output

# Place -I options here
CINCS = 

# Place extra C/CXX arguments here
CEXTRA = -mfpu=fpv4-sp-d16 -mfloat-abi=softfp

# Source files for C compiler
SRC = main.c

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.stm32f4.inc
-include ~/.gEDA/Makefile.stm32f4.inc

