# Target device
MCU = attiny85
F_CPU = 16000000
UPLOAD_RATE = 115200 #19200
LFUSE = 0xE1
HFUSE = 0xDD
EFUSE = 0xFF

# Application files and targets
TARGET = output

# Place -I options here
CINCS = 
CXXINCS = 

# Place extra C/CXX arguments here
CEXTRA = 
CXXEXTRA = 

# Source files for C compiler
SRC = 

# Source files for C++ compiler
CXXSRC = 

# Source files in assembly
ASRC =

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.avr.inc
-include ~/.gEDA/Makefile.avr.inc
