# Application files and targets
TARGET = output
PSP_EBOOT_TITLE = $(TARGET)

# Place -I options here
CINCS =

# Place extra C/CXX arguments here
CEXTRA =

# Source files for C compiler
SRC = main.c

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.psp.inc

