# Target device
MCU=msp430g2553

# Application files and targets
TARGET = output

# Place -I options here
CINCS = 

# Place extra C/CXX arguments here
CEXTRA = 

# Source files for C compiler
SRC = 

# This includes the rest of rules DO NOT DELETE
-include ~/Dropbox/EDA/Makefile.msp430.inc
-include ~/.gEDA/Makefile.msp430.inc

